# YOLOv8 architecture with SE in the neck
nc: 3  # number of classes (branch, burl, intersection)
depth_multiple: 0.33
width_multiple: 0.50

backbone:
  # [from, number, module, args]
  - [[-1], 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [[-1], 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [[-1], 3, C2f, [128, True]]  # 2
  - [[-1], 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [[-1], 6, C2f, [256, True]]  # 4
  - [[-1], 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [[-1], 6, C2f, [512, True]]  # 6
  - [[-1], 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [[-1], 3, C2f, [1024, True]]  # 8
  - [[-1], 1, SPPF, [1024, 5]]  # 9

neck:
  # Adding SE after concatenation
  - [[-1], 1, Upsample, [None, 2, 'nearest']]  # 10
  - [[-1, 6], 1, Concat, [1]]  # 11
  - [[-1], 1, SE, [512]]  # 12 (SE module)
  - [[-1], 3, C2f, [512, True]]  # 13
  - [[-1], 1, Upsample, [None, 2, 'nearest']]  # 14
  - [[-1, 4], 1, Concat, [1]]  # 15
  - [[-1], 1, SE, [256]]  # 16 (SE module)
  - [[-1], 3, C2f, [256, True]]  # 17
  - [[-1], 1, Conv, [256, 3, 2]]  # 18
  - [[-1, 13], 1, Concat, [1]]  # 19
  - [[-1], 1, SE, [512]]  # 20 (SE module)
  - [[-1], 3, C2f, [512, True]]  # 21
  - [[-1, 9], 1, Concat, [1]]  # 22
  - [[-1], 1, SE, [1024]]  # 23 (SE module)
  - [[-1], 3, C2f, [1024, True]]  # 24

head:
  - [[-1], 1, Detect, [nc, anchors]]  # Detect(nc=3)