# YOLOv8 architecture with enhanced neck (no custom modules)
nc: 3  # number of classes (branch, burl, intersection)
depth_multiple: 0.33
width_multiple: 0.50

backbone:
  # [from, number, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]  # 2
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]  # 4
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]  # 6
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]  # 8
  - [-1, 1, SPPF, [1024, 5]]  # 9

neck:
  # Enhanced with reduced C2f depth and SPPF
  - [-1, 1, Upsample, [None, 2, 'nearest']]  # 10
  - [[-1, 6], 1, Concat, [1]]  # 11
  - [-1, 2, C2f, [512, True]]  # 12 (reduced depth from 4 to 2)
  - [-1, 1, Upsample, [None, 2, 'nearest']]  # 13
  - [[-1, 4], 1, Concat, [1]]  # 14
  - [-1, 2, C2f, [256, True]]  # 15 (reduced depth from 4 to 2)
  - [-1, 1, Conv, [256, 3, 2]]  # 16
  - [[-1, 12], 1, Concat, [1]]  # 17
  - [-1, 2, C2f, [512, True]]  # 18 (reduced depth from 4 to 2)
  - [-1, 1, SPPF, [512, 5]]  # 19 (added SPPF)
  - [-1, 1, Conv, [512, 3, 2]]  # 20
  - [[-1, 9], 1, Concat, [1]]  # 21
  - [-1, 2, C2f, [1024, True]]  # 22 (reduced depth from 4 to 2)

head:
  - [[-1], 1, Detect, [nc]]  # Detect(nc=3)